### ISSUE TITLE
Clean UP & Dockerization eos5ecc

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos5ecc#2]

**Comment by emmakodes** [comment]
Hello @GemmaTuron I get the following error when I try to fetch the model:
```
Traceback (most recent call last):
  File "/usr/local/envs/ersilia/bin/ersilia", line 33, in <module>
    sys.exit(load_entry_point('ersilia', 'console_scripts', 'ersilia')())
  File "/usr/local/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/local/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/content/ersilia/ersilia/cli/commands/fetch.py", line 73, in fetch
    _fetch(mf, model_id)
  File "/content/ersilia/ersilia/cli/commands/fetch.py", line 12, in _fetch
    mf.fetch(model_id)
  File "/content/ersilia/ersilia/hub/fetch/fetch.py", line 305, in fetch
    self._fetch_not_from_dockerhub(model_id=model_id)
  File "/content/ersilia/ersilia/hub/fetch/fetch.py", line 263, in _fetch_not_from_dockerhub
    self._content()
  File "/content/ersilia/ersilia/hub/fetch/fetch.py", line 233, in _content
    cg.get()
  File "/content/ersilia/ersilia/hub/fetch/actions/content.py", line 19, in get
    card = self.mc.get(self.model_id, as_json=False)
  File "/content/ersilia/ersilia/hub/content/card.py", line 736, in get
    card = self._get(model_id)
  File "/content/ersilia/ersilia/hub/content/card.py", line 725, in _get
    card = self.mc.get(model_id)
  File "/content/ersilia/ersilia/hub/content/card.py", line 578, in get
    data = json.load(f)
  File "/usr/local/envs/ersilia/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/envs/ersilia/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/envs/ersilia/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/envs/ersilia/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 17 column 1 (char 289)
```
<br>
I guess the metadata of the model is not configured or does ersilia work with `STRING with IUPAC NAMES`?

**Comment by GemmaTuron** [comment]
Sorry @emmakodes, this model is on hold because Ersilia could not accept text as input, we are working on it but haven't finished.
Would you [have a look](https://github.com/ersilia-os/ersilia/issues/603) and help us out here once you are done with `eos3ae7`?

**Comment by emmakodes** [comment]
Sure @GemmaTuron I will start with this once I'm done with `eos3ae7`

**Comment by GemmaTuron** [comment]
I'll close this issue and leave the model request issue open only to centralise the conversation
